# Generated by Django 5.0 on 2024-02-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customuser_matchstate_match_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='polls.customuser'),
        ),
    ]
