# Generated by Django 5.0 on 2024-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_customuser_is_42_user_customuser_refresh_token42_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token42',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
