# Generated by Django 5.0 on 2024-02-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_customuser_token42'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id42',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_42_user',
            field=models.BooleanField(default=False),
        ),
    ]
