# Generated by Django 5.0 on 2024-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_customuser_id42_alter_customuser_is_42_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('joiningGame', 'Joining Game'), ('inGame', 'In Game')], default='disconnected', max_length=20),
        ),
    ]
