# Generated by Django 5.0 on 2024-04-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_matchpreview_players_alter_matchpreview_host'),
        ('polls', '0007_customuser_game_room_name_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaking.matchpreview'),
        ),
    ]
