# Generated by Django 5.0 on 2024-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpreview',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
